export type AlbumResponse<T> = {
  data?: T | undefined;
  success: boolean;
  status: number;
};

export type Album = {
  id: string;
  title: string;
  description: string | null;
  datetime: number;
  cover: string;
  cover_width: number;
  cover_height: number;
  account_url: string;
  account_id: number;
  privacy: string;
  layout: string;
  views: number;
  link: string;
  ups: number;
  downs: number;
  points: number;
  score: number;
  is_album: boolean;
  vote: string | null;
  favorite: boolean;
  nsfw: boolean;
  section: string;
  comment_count: number;
  favorite_count: number;
  topic: string | null;
  topic_id: string | null;
  images_count: number;
  in_gallery: boolean;
  is_ad: boolean;
  tags: Tag[];
  ad_type: number;
  ad_url: string;
  in_most_viral: boolean;
  include_album_ads: boolean;
  images: Image[];
  ad_config: AdConfig;
};

export type Tag = {
  name: string;
  display_name: string;
  followers: number;
  total_items: number;
  following: boolean;
  is_whitelisted: boolean;
  background_hash: string;
  thumbnail_hash: string | null;
  accent: string;
  background_is_animated: boolean;
  thumbnail_is_animated: boolean;
  is_promoted: boolean;
  description: string;
  logo_hash: string | null;
  logo_destination_url: string | null;
  description_annotations: object;
};

export type Image = {
  id: string;
  title: string | null;
  description: string | null;
  datetime: number;
  type: string;
  animated: boolean;
  width: number;
  height: number;
  size: number;
  views: number;
  bandwidth: number;
  vote: string | null;
  favorite: boolean;
  nsfw: boolean | null;
  section: string | null;
  account_url: string | null;
  account_id: number | null;
  is_ad: boolean;
  in_most_viral: boolean;
  has_sound: boolean;
  tags: string[];
  ad_type: number;
  ad_url: string;
  edited: string;
  in_gallery: boolean;
  link: string;
  comment_count: number | null;
  favorite_count: number | null;
  ups: number | null;
  downs: number | null;
  points: number | null;
  score: number | null;
};

export type AdConfig = {
  safeFlags: string[];
  highRiskFlags: string[];
  unsafeFlags: string[];
  wallUnsafeFlags: string[];
  showsAds: boolean;
  showAdLevel: number;
  safe_flags: string[];
  high_risk_flags: string[];
  unsafe_flags: string[];
  wall_unsafe_flags: string[];
  show_ads: boolean;
  show_ad_level: number;
  nsfw_score: number;
};
