import { AlbumFilter } from "@/components/album-search/AlbumFilter";
import { AlbumSearch } from "@/components/album-search/AlbumSearch";
import { AlbumCardDetail } from "@/components/album/AlbumCardDetail";
import type { Metadata } from "next";
import { getAlbums } from "../api/albums/getAlbums";

export const metadata: Metadata = {
  title: "Album Slug Layout",
  description: "Generated by create rk-stack",
};

interface Props {
  children: Readonly<React.ReactNode>;
  searchParams?: Promise<{
    term?: string;
    filter?: string;
  }>;
}

export default async function Layout(props: Props) {
  const searchParams = await props.searchParams;
  const albums = await getAlbums({ searchParams });

  return (
    <div className="3xl:container mx-auto py-8 pb-20 flex flex-col gap-8 h-full px-8 sm:px-20 md:px-8 2xl:px-8">
      {props.children}
      <div className="flex flex-col gap-2">
        <h3 className="text-xl font-bold text-left">Search More Albums</h3>
        <div className="flex gap-4">
          <AlbumSearch />
          <AlbumFilter />
        </div>
      </div>
      <div className="grid grid-cols-1 gap-3">
        {albums.map((album) => (
          <AlbumCardDetail key={album.id} album={album} />
        ))}
      </div>
    </div>
  );
}
